set columns=120
set lines=40

if has('macunix')
  set guifont=Source\ Han\ Code\ JP\ N:h11
  set antialias
  set macthinstrokes
elseif has('unix')
  set guifont=Source\ Han\ Code\ JP\ N\ 8
  set antialias
endif

set guioptions-=T
